/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int HEXIDECIMAL = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int INTLIT = 12;
  /** RegularExpression Id. */
  int UNICODE = 13;
  /** RegularExpression Id. */
  int OTHER = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"begin\"",
    "\"end\"",
    "<DIGIT>",
    "<LETTER>",
    "<HEXIDECIMAL>",
    "<ID>",
    "<INTLIT>",
    "<UNICODE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<OTHER>",
  };

}
